services:
  api-gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: arseniherasimovichinnowise/api-gateway
    ports:
      - '8080:8080'
    networks:
      - backend-net

  user-service:
    image: arseniherasimovichinnowise/user-service:latest
    depends_on:
      - user-service-db
      - user-service-redis
    networks:
      - backend-net
      - user-service-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_SECONDARY_PROFILE=dev
      - APP_LOGGING_LEVEL=debug
      - DB_HOST=user-service-db
      - DB_USER=${USER_DB_USER}
      - DB_PASSWORD=${USER_DB_PASSWORD}
      - DB_NAME=${USER_DB_NAME}
      - REDIS_HOST=user-service-redis
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  user-service-db:
    image: postgres:15
    volumes:
      - user-service-postgres-data:/var/lib/postgresql/data
    networks:
      - user-service-net
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}

  user-service-redis:
    image: redis:7
    volumes:
      - user-service-redis-data:/data
    networks:
      - user-service-net
    command: redis-server --appendonly yes

  discovery-service:
    image: arseniherasimovichinnowise/discovery-service:latest
    ports:
      - '8761'
    networks:
      - backend-net
    environment:
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  order-service:
    image: arseniherasimovichinnowise/order-service:latest
    depends_on:
      - order-service-db
    networks:
      - backend-net
      - order-service-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - APP_LOGGING_LEVEL=debug
      - DB_HOST=order-service-db
      - DB_USER=${ORDER_DB_USER}
      - DB_PASSWORD=${ORDER_DB_PASSWORD}
      - DB_NAME=${ORDER_DB_NAME}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  order-service-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
    networks:
      - order-service-net
    volumes:
      - order-service-postgres-data:/var/lib/postgresql/data


  auth-service:
    image: arseniherasimovichinnowise/auth-service:latest
    depends_on:
      - auth-service-db
    networks:
      - backend-net
      - auth-service-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=auth-service-db
      - DB_USER=${AUTH_DB_USER}
      - DB_PASSWORD=${AUTH_DB_PASSWORD}
      - DB_NAME=${AUTH_DB_NAME}
      - APP_LOGGING_LEVEL=debug
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - JWT_SECRET=${AUTH_JWT_SECRET}

  auth-service-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    networks:
      - auth-service-net
    volumes:
      - auth-service-postgres-data:/var/lib/postgresql/data


volumes:
  user-service-postgres-data: {}
  user-service-redis-data: {}
  order-service-postgres-data: {}
  auth-service-postgres-data: {}

networks:
  backend-net:
    external: true
  user-service-net:
    driver: bridge
  order-service-net:
    driver: bridge
  auth-service-net:
    driver: bridge